added custom error handling via callback function
DigitalGlobe/jetset pull request #6
Opened 2017-05-25 21:24 UTC by maxwell-oroark

2017-05-26 01:17 UTC, glortho requested changes

2017-05-26 01:17 UTC, glortho commented on src/api/routes.js
> +        ? { method: methodDict[ methodKey ], route: config, getData: options.getData || ( data => data ), onError: options.onError || (error => error) }
@maxwell-oroark i'm thinking our no-op should return a rejected promise so that any `catch` handlers down the line will be invoked

2017-05-26 15:40 UTC, maxwell-oroark commented on src/api/routes.js
> +        ? { method: methodDict[ methodKey ], route: config, getData: options.getData || ( data => data ), onError: options.onError || (error => error) }
so return the error in the reject() or, reject() and then return error? 
```
error => Promise.reject(error)
```
```
error => {
Promise.reject(error)
return error
}
```

2017-05-26 16:14 UTC, maxwell-oroark commented on src/api/routes.js
> +        ? { method: methodDict[ methodKey ], route: config, getData: options.getData || ( data => data ), onError: options.onError || (error => error) }
@glortho  ^

2017-05-26 19:57 UTC, glortho commented
oh also @maxwell-oroark we should update docs/index.md

2017-05-28 22:24 UTC, maxwell-oroark commented
@glortho - documenatation updated 👍

2017-05-30 16:53 UTC, glortho commented on docs/index.md
> +  route?:   string | (config) object
@maxwell-oroark this should still return just a string

2017-05-30 16:54 UTC, glortho commented on docs/index.md
> +  route?:   string | (config) object
`onError` is just another possible member of `RouteConfig`

2017-05-30 16:54 UTC, glortho commented
looking good @maxwell-oroark ! one minor correction to the docs we should do, but i'll won't hold up merge for it.

2017-05-30 16:54 UTC, merged